"""
PyXcel — PDF Engine
Exports Excel sheets to styled PDF reports using reportlab.
"""
import pandas as pd
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph,
    Spacer, HRFlowable, PageBreak
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT
import os
from datetime import datetime

C = {
    "primary" : colors.HexColor("#7c83ff"),
    "bg_dark" : colors.HexColor("#1a1d2e"),
    "bg_darker": colors.HexColor("#13151f"),
    "text"    : colors.HexColor("#e0e0e0"),
    "muted"   : colors.HexColor("#888888"),
    "green"   : colors.HexColor("#4caf81"),
    "border"  : colors.HexColor("#2a2d3e"),
    "white"   : colors.white,
}


def export_sheet_to_pdf(filepath, sheet, output_path, title="", include_summary=True, max_rows=500):
    try:
        df        = pd.read_excel(filepath, sheet_name=sheet)
        truncated = len(df) > max_rows
        if truncated:
            df = df.head(max_rows)

        doc   = SimpleDocTemplate(output_path, pagesize=landscape(A4),
                                  rightMargin=1.5*cm, leftMargin=1.5*cm,
                                  topMargin=1.5*cm, bottomMargin=1.5*cm)
        story = []

        title_style = ParagraphStyle("T", fontSize=20, textColor=C["primary"],
                                     spaceAfter=6, alignment=TA_CENTER, fontName="Helvetica-Bold")
        sub_style   = ParagraphStyle("S", fontSize=10, textColor=C["muted"],
                                     spaceAfter=4, alignment=TA_CENTER)

        story.append(Paragraph(title or f"PyXcel Report — {sheet}", title_style))
        story.append(Paragraph(
            f"Generated by PyXcel AI  ·  {datetime.now().strftime('%B %d, %Y %H:%M')}  ·  "
            f"Sheet: {sheet}  ·  Rows: {len(df)}  ·  Columns: {len(df.columns)}", sub_style))
        story.append(HRFlowable(width="100%", thickness=1, color=C["primary"], spaceAfter=12))

        if include_summary:
            numeric_cols = df.select_dtypes(include="number").columns
            if len(numeric_cols) > 0:
                story.append(Paragraph("Summary Statistics",
                    ParagraphStyle("H", fontSize=11, textColor=C["primary"], spaceAfter=6, fontName="Helvetica-Bold")))
                summary_data = [["Column","Count","Sum","Average","Min","Max"]]
                for col in numeric_cols[:8]:
                    d = df[col].dropna()
                    summary_data.append([str(col), str(len(d)), f"{d.sum():,.2f}", f"{d.mean():,.2f}", f"{d.min():,.2f}", f"{d.max():,.2f}"])
                t = Table(summary_data, colWidths=[3*cm,2*cm,3*cm,3*cm,3*cm,3*cm])
                t.setStyle(TableStyle([
                    ("BACKGROUND",(0,0),(-1,0),C["bg_dark"]),("TEXTCOLOR",(0,0),(-1,0),C["primary"]),
                    ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),("FONTSIZE",(0,0),(-1,-1),9),
                    ("BACKGROUND",(0,1),(-1,-1),C["bg_darker"]),("TEXTCOLOR",(0,1),(-1,-1),C["text"]),
                    ("ROWBACKGROUNDS",(0,1),(-1,-1),[C["bg_darker"],C["bg_dark"]]),
                    ("GRID",(0,0),(-1,-1),0.5,C["border"]),("ALIGN",(1,0),(-1,-1),"CENTER"),
                    ("VALIGN",(0,0),(-1,-1),"MIDDLE"),("TOPPADDING",(0,0),(-1,-1),5),("BOTTOMPADDING",(0,0),(-1,-1),5),
                ]))
                story.append(t)
                story.append(Spacer(1, 0.3*inch))

        story.append(Paragraph("Data", ParagraphStyle("DT", fontSize=11, textColor=C["primary"], spaceAfter=6, fontName="Helvetica-Bold")))
        if truncated:
            story.append(Paragraph(f"Showing first {max_rows} rows",
                ParagraphStyle("W", fontSize=8, textColor=C["muted"])))

        headers   = [str(c) for c in df.columns][:12]
        col_count = len(headers)
        table_data = [headers]
        for _, row in df.iterrows():
            table_data.append([str(v)[:25] if v is not None and str(v) != "nan" else "" for v in list(row)[:12]])

        page_width = landscape(A4)[0] - 3*cm
        col_width  = page_width / col_count
        dt = Table(table_data, colWidths=[col_width]*col_count, repeatRows=1)
        dt.setStyle(TableStyle([
            ("BACKGROUND",(0,0),(-1,0),C["bg_dark"]),("TEXTCOLOR",(0,0),(-1,0),C["primary"]),
            ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),("FONTSIZE",(0,0),(-1,0),8),
            ("ALIGN",(0,0),(-1,0),"CENTER"),
            ("FONTNAME",(0,1),(-1,-1),"Helvetica"),("FONTSIZE",(0,1),(-1,-1),7),
            ("TEXTCOLOR",(0,1),(-1,-1),C["text"]),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[C["bg_darker"],C["bg_dark"]]),
            ("GRID",(0,0),(-1,-1),0.3,C["border"]),("VALIGN",(0,0),(-1,-1),"MIDDLE"),
            ("TOPPADDING",(0,0),(-1,-1),4),("BOTTOMPADDING",(0,0),(-1,-1),4),
            ("LEFTPADDING",(0,0),(-1,-1),4),("RIGHTPADDING",(0,0),(-1,-1),4),
        ]))
        story.append(dt)
        story.append(Spacer(1, 0.2*inch))
        story.append(HRFlowable(width="100%", thickness=0.5, color=C["border"]))
        story.append(Paragraph("PyXcel — AI-Powered Spreadsheet System  ·  KiTE Development Team",
            ParagraphStyle("F", fontSize=7, textColor=C["muted"], alignment=TA_CENTER)))

        doc.build(story)
        return {"status": "success", "output_path": output_path, "rows": len(df),
                "cols": col_count, "truncated": truncated,
                "message": f"PDF exported to {os.path.basename(output_path)}"}
    except Exception as e:
        return {"status": "error", "message": str(e)}


def export_all_sheets_to_pdf(filepath, output_path, title=""):
    try:
        import openpyxl
        wb     = openpyxl.load_workbook(filepath, read_only=True)
        sheets = wb.sheetnames
        wb.close()

        doc   = SimpleDocTemplate(output_path, pagesize=landscape(A4),
                                  rightMargin=1.5*cm, leftMargin=1.5*cm,
                                  topMargin=1.5*cm, bottomMargin=1.5*cm)
        story = []

        story.append(Paragraph(title or "PyXcel Full Report",
            ParagraphStyle("T", fontSize=22, textColor=C["primary"], alignment=TA_CENTER,
                           fontName="Helvetica-Bold", spaceAfter=8)))
        story.append(Paragraph(
            f"Generated: {datetime.now().strftime('%B %d, %Y %H:%M')}  ·  Sheets: {len(sheets)}",
            ParagraphStyle("S", fontSize=10, textColor=C["muted"], alignment=TA_CENTER)))
        story.append(PageBreak())

        for sheet in sheets:
            try:
                df = pd.read_excel(filepath, sheet_name=sheet)
                if df.empty:
                    continue
                story.append(Paragraph(f"Sheet: {sheet}",
                    ParagraphStyle("ST", fontSize=14, textColor=C["primary"],
                                   fontName="Helvetica-Bold", spaceAfter=8)))
                headers    = [str(c) for c in df.columns][:12]
                table_data = [headers]
                for _, row in df.head(100).iterrows():
                    table_data.append([str(v)[:20] if v is not None and str(v) != "nan" else "" for v in list(row)[:12]])
                page_width = landscape(A4)[0] - 3*cm
                col_width  = page_width / len(headers)
                t = Table(table_data, colWidths=[col_width]*len(headers), repeatRows=1)
                t.setStyle(TableStyle([
                    ("BACKGROUND",(0,0),(-1,0),C["bg_dark"]),("TEXTCOLOR",(0,0),(-1,0),C["primary"]),
                    ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),("FONTSIZE",(0,0),(-1,-1),7),
                    ("TEXTCOLOR",(0,1),(-1,-1),C["text"]),
                    ("ROWBACKGROUNDS",(0,1),(-1,-1),[C["bg_darker"],C["bg_dark"]]),
                    ("GRID",(0,0),(-1,-1),0.3,C["border"]),("VALIGN",(0,0),(-1,-1),"MIDDLE"),
                    ("TOPPADDING",(0,0),(-1,-1),3),("BOTTOMPADDING",(0,0),(-1,-1),3),
                ]))
                story.append(t)
                story.append(PageBreak())
            except Exception:
                continue

        doc.build(story)
        return {"status": "success", "output_path": output_path, "sheets": len(sheets),
                "message": "All sheets exported to PDF"}
    except Exception as e:
        return {"status": "error", "message": str(e)}
